-- Schema em PostgreSQL. Traduzido de schema.sql (SQLite), que segue valendo
-- para o desenvolvimento local em arquivo.
--
-- Diferenças que exigiram decisão, e não conversão mecânica:
--   * AUTOINCREMENT           -> GENERATED BY DEFAULT AS IDENTITY
--   * TEXT com datetime('now')-> TIMESTAMPTZ com now(). O driver devolve ISO 8601
--                                (ver setTypeParser em db/index.ts), então o
--                                contrato de string do app continua o mesmo.
--   * email COLLATE NOCASE    -> índice único sobre lower(email)
--   * 0/1 para booleanos      -> mantidos como INTEGER de propósito, para não
--                                espalhar mudança de tipo por toda a aplicação

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          TEXT        NOT NULL,
  email         TEXT        NOT NULL,
  password_hash TEXT        NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Substitui o COLLATE NOCASE do SQLite: dois e-mails que só diferem em maiúsculas
-- continuam sendo o mesmo usuário.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (lower(email));

CREATE TABLE IF NOT EXISTS book_works (
  id                 INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ol_work_key        TEXT        NOT NULL UNIQUE,
  title              TEXT        NOT NULL,
  authors            TEXT        NOT NULL DEFAULT '[]',
  cover_id           INTEGER,
  cover_url          TEXT,
  first_publish_year INTEGER,
  subjects           TEXT        NOT NULL DEFAULT '[]',
  synced_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS book_editions (
  id               INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  work_id          INTEGER     NOT NULL REFERENCES book_works(id) ON DELETE CASCADE,
  ol_edition_key   TEXT        UNIQUE,
  title            TEXT        NOT NULL,
  publisher        TEXT,
  publish_date     TEXT,
  number_of_pages  INTEGER,
  isbn             TEXT,
  language         TEXT,
  cover_id         INTEGER,
  cover_url        TEXT,
  is_custom        INTEGER     NOT NULL DEFAULT 0,
  synced_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_editions_work ON book_editions(work_id);

CREATE TABLE IF NOT EXISTS user_library (
  id           INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id      INTEGER     NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
  edition_id   INTEGER     NOT NULL REFERENCES book_editions(id) ON DELETE CASCADE,
  status       TEXT        NOT NULL DEFAULT 'WANT_TO_READ'
               CHECK (status IN ('WANT_TO_READ','READING','PAUSED','FINISHED','ABANDONED')),
  total_pages  INTEGER     CHECK (total_pages IS NULL OR total_pages > 0),
  current_page INTEGER     NOT NULL DEFAULT 0 CHECK (current_page >= 0),
  rating       INTEGER     CHECK (rating IS NULL OR (rating BETWEEN 1 AND 5)),
  is_favorite  INTEGER     NOT NULL DEFAULT 0,
  notes        TEXT,
  added_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at   TIMESTAMPTZ,
  finished_at  TIMESTAMPTZ,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, edition_id)
);
CREATE INDEX IF NOT EXISTS idx_library_user_status ON user_library(user_id, status);

CREATE TABLE IF NOT EXISTS reading_progress (
  id              INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  library_item_id INTEGER     NOT NULL REFERENCES user_library(id) ON DELETE CASCADE,
  page_from       INTEGER     NOT NULL CHECK (page_from >= 0),
  page_to         INTEGER     NOT NULL CHECK (page_to   >= 0),
  pages_read      INTEGER     NOT NULL,
  note            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_progress_item ON reading_progress(library_item_id, created_at DESC);

CREATE TABLE IF NOT EXISTS annotations (
  id              INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  library_item_id INTEGER     NOT NULL REFERENCES user_library(id) ON DELETE CASCADE,
  page            INTEGER     CHECK (page IS NULL OR page >= 0),
  title           TEXT,
  content         TEXT        NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annotations_item ON annotations(library_item_id, created_at DESC);

CREATE TABLE IF NOT EXISTS quotes (
  id              INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  library_item_id INTEGER     NOT NULL REFERENCES user_library(id) ON DELETE CASCADE,
  page            INTEGER     CHECK (page IS NULL OR page >= 0),
  text            TEXT        NOT NULL,
  comment         TEXT,
  is_favorite     INTEGER     NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_quotes_item ON quotes(library_item_id, created_at DESC);
